version: '3.3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/data
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  mongodb:
    image: 'mongo:3.4.1'
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:

      MONGO_INITDB_DATABASE: 'mongodb'
      MONGO_INITDB_ROOT_USERNAME : 'mongodb'
      MONGO_INITDB_ROOT_PASSWORD : 'mongodb'
volumes:
  rabbitmqdata:
  mongodbdata: